//
//  index.ts
//
//  The MIT License
//  Copyright (c) 2021 - 2025 O2ter Limited. All rights reserved.
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in
//  all copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
//  THE SOFTWARE.
//

import { PropType } from './attrs';

export const HTMLElementTagNameMap = {
  "a": {
    attributionSrc: PropType.string,
  },
  "abbr": {},
  "address": {},
  "area": {},
  "article": {},
  "aside": {},
  "audio": {},
  "b": {},
  "base": {},
  "bdi": {},
  "bdo": {},
  "blockquote": {},
  "body": {},
  "br": {},
  "button": {},
  "canvas": {},
  "caption": {},
  "cite": {},
  "code": {},
  "col": {},
  "colgroup": {},
  "data": {},
  "datalist": {},
  "dd": {},
  "del": {},
  "details": {},
  "dfn": {},
  "dialog": {},
  "div": {},
  "dl": {},
  "dt": {},
  "em": {},
  "embed": {},
  "fieldset": {},
  "figcaption": {},
  "figure": {},
  "footer": {},
  "form": {},
  "h1": {},
  "h2": {},
  "h3": {},
  "h4": {},
  "h5": {},
  "h6": {},
  "head": {},
  "header": {},
  "hgroup": {},
  "hr": {},
  "html": {},
  "i": {},
  "iframe": {},
  "img": {},
  "input": {},
  "ins": {},
  "kbd": {},
  "label": {},
  "legend": {},
  "li": {},
  "link": {},
  "main": {},
  "map": {},
  "mark": {},
  "menu": {},
  "meta": {},
  "meter": {},
  "nav": {},
  "noscript": {},
  "object": {},
  "ol": {},
  "optgroup": {},
  "option": {},
  "output": {},
  "p": {},
  "picture": {},
  "pre": {},
  "progress": {},
  "q": {},
  "rp": {},
  "rt": {},
  "ruby": {},
  "s": {},
  "samp": {},
  "script": {},
  "search": {},
  "section": {},
  "select": {},
  "slot": {},
  "small": {},
  "source": {},
  "span": {},
  "strong": {},
  "style": {},
  "sub": {},
  "summary": {},
  "sup": {},
  "table": {},
  "tbody": {},
  "td": {},
  "template": {},
  "textarea": {},
  "tfoot": {},
  "th": {},
  "thead": {},
  "time": {},
  "title": {},
  "tr": {},
  "track": {},
  "u": {},
  "ul": {},
  "var": {},
  "video": {},
  "wbr": {},
} as const;

export const HTMLElementDeprecatedTagNameMap = {
  "acronym": {},
  "applet": {},
  "basefont": {},
  "bgsound": {},
  "big": {},
  "blink": {},
  "center": {},
  "dir": {},
  "font": {},
  "frame": {},
  "frameset": {},
  "isindex": {},
  "keygen": {},
  "listing": {},
  "marquee": {},
  "menuitem": {},
  "multicol": {},
  "nextid": {},
  "nobr": {},
  "noembed": {},
  "noframes": {},
  "param": {},
  "plaintext": {},
  "rb": {},
  "rtc": {},
  "spacer": {},
  "strike": {},
  "tt": {},
  "xmp": {},
} as const;

export const SVGElementTagNameMap = {
  "a": {},
  "animate": {},
  "animateMotion": {},
  "animateTransform": {},
  "circle": {},
  "clipPath": {},
  "defs": {},
  "desc": {},
  "ellipse": {},
  "feBlend": {},
  "feColorMatrix": {},
  "feComponentTransfer": {},
  "feComposite": {},
  "feConvolveMatrix": {},
  "feDiffuseLighting": {},
  "feDisplacementMap": {},
  "feDistantLight": {},
  "feDropShadow": {},
  "feFlood": {},
  "feFuncA": {},
  "feFuncB": {},
  "feFuncG": {},
  "feFuncR": {},
  "feGaussianBlur": {},
  "feImage": {},
  "feMerge": {},
  "feMergeNode": {},
  "feMorphology": {},
  "feOffset": {},
  "fePointLight": {},
  "feSpecularLighting": {},
  "feSpotLight": {},
  "feTile": {},
  "feTurbulence": {},
  "filter": {},
  "foreignObject": {},
  "g": {},
  "image": {},
  "line": {},
  "linearGradient": {},
  "marker": {},
  "mask": {},
  "metadata": {},
  "mpath": {},
  "path": {},
  "pattern": {},
  "polygon": {},
  "polyline": {},
  "radialGradient": {},
  "rect": {},
  "script": {},
  "set": {},
  "stop": {},
  "style": {},
  "svg": {},
  "switch": {},
  "symbol": {},
  "text": {},
  "textPath": {},
  "title": {},
  "tspan": {},
  "use": {},
  "view": {},
} as const;

export const MathMLElementTagNameMap = {
  "annotation": {},
  "annotation-xml": {},
  "maction": {},
  "math": {},
  "merror": {},
  "mfrac": {},
  "mi": {},
  "mmultiscripts": {},
  "mn": {},
  "mo": {},
  "mover": {},
  "mpadded": {},
  "mphantom": {},
  "mprescripts": {},
  "mroot": {},
  "mrow": {},
  "ms": {},
  "mspace": {},
  "msqrt": {},
  "mstyle": {},
  "msub": {},
  "msubsup": {},
  "msup": {},
  "mtable": {},
  "mtd": {},
  "mtext": {},
  "mtr": {},
  "munder": {},
  "munderover": {},
  "semantics": {},
} as const;
